# https://www.playframework.com/documentation/latest/Configuration
play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  # 1. List oif allowed hosts
  allowedOrigins = ["http://localhost:3000", "http://localhost:4200"]

  # 2. Allowed methods
  allowedHttpMethods = ["GET", "POST", "PATCH", "DELETE"]

  # 3. Allowed headers
  allowedHttpHeaders = ["Accept", "Content-Type", "Origin", "X-Json", "X-Prototype-Version", "X-Requested-With"]

  serveForbidden = true
}

play.filters.hosts {
  allowed = ["."]
}