version: '3.8'

networks:
  my-network:
    driver: bridge

services:
  backend-service:
    image: ghcr.io/jheczko/ebiznes_course-backend:latest
    container_name: go-backend-service
    ports:
      - "13000:13000"
    networks:
      - my-network
    env_file:
      - .env
    restart: always

  frontend-service:
    image: ghcr.io/jheczko/ebiznes_course-frontend:latest
    container_name: react-frontend-service
    ports:
      - "5173:8080"
    depends_on:
      - backend-service
    networks:
      - my-network
    restart: always